version: '3.7'

services:
  app:
    image: chialab/php:7.2
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:8000:80
    restart: unless-stopped
    command: php artisan serve --host=0.0.0.0 --port=80
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hky
